name: Artavista Auto Deploy
on:
  push:
    branches: [ main ] # Jalan otomatis tiap kamu push ke branch main


jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Power Platform CLI Deploy
        shell: pwsh
        run: |
          # 1. Download & Install PAC CLI di server GitHub
          $msiPath = "$env:TEMP\pac.msi"
          Invoke-WebRequest -Uri "https://aka.ms/PowerAppsCLI.msi" -OutFile $msiPath
          Start-Process msiexec.exe -ArgumentList "/i $msiPath /qn" -Wait
          
          # 2. Tambahkan ke PATH agar bisa dipanggil
          $env:Path += ";C:\Program Files\Microsoft Power Apps CLI\bin"
          
          # 3. Login & Push menggunakan Rahasia yang tadi kita buat
          pac auth create --url ${{ secrets.ENVIRONMENT_URL }} --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
          pac pcf push --publisher-prefix arta