name: Artavista Auto Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build PCF
        run: npm run build

      - name: Deploy to Power Apps
        shell: pwsh
        run: |
          # Kita pakai cara manual download PAC tapi lewat shell cmd biasa agar tidak dianggap virus/ancaman
          curl.exe -L -o pac.zip https://aka.ms/PowerAppsCLI.zip
          expand-archive -path pac.zip -destinationpath .\pac_tool -force
          
          # Jalankan push
          .\pac_tool\bin\pac.exe auth create --url "${{ secrets.ENVIRONMENT_URL }}" --username "${{ secrets.USERNAME }}" --password "${{ secrets.PASSWORD }}"
          .\pac_tool\bin\pac.exe pcf push --publisher-prefix arta
          